### ISSUE TITLE
Remove CircleCI config & use Github Actions

### ISSUE THREAD

**Issue by mawburn** [mawburn/portaler-core#67]
We don't really need the CircleCI dependency and can use the CircleCI action to publish to Docker. 

Something like this should be all we need for the different pieces. I don't know off the top of my head how to add the version number to instead of just `:latest` but I'm sure that would be something easy to figure out. 

```YAML
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mawburn/portaler:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
```

https://docs.github.com/en/actions/quickstart
